### ISSUE TITLE
remake background/city/ground/trees

### ISSUE THREAD

**Issue by TheThirdOne** [eshsprogramming/squishy-eno#5]
make it like the engineering lab

**Comment by TheThirdOne** [comment]
anyone want to claim any part of this

**Comment by Nick-Mazuk** [comment]
We could always have different themes for different parts of the year, e.i. we could have a Halloween theme during October or a Holiday theme during December.

**Comment by TheThirdOne** [comment]
I like that idea, but someone still needs to put some work on actually doing it.

**Comment by TheThirdOne** [comment]
@XDleader555 Would you care to make an Easter edition?

**Comment by TheThirdOne** [comment]
Also I am going to pop out @Nick-Mazuk's idea for themes into a different issue.

**Comment by Nick-Mazuk** [comment]
I think we need to remake the background again just to make it more discernible from the foreground. Right now, it looks visually confusing.
